#include "tester.c"
#include "tester_command_line_parser.c"
#include "tester_summary.c"
#if   OS_LINUX
    #include "tester_memory_tracking_linux.c"
#elif OS_MAC
    #include "tester_memory_tracking_mac.c"
#endif
#include "tester_debug_information_builder.c"

// Part 1 - Libc Functions
#include "test/ft_isalpha.c"
#include "test/ft_isdigit.c"
#include "test/ft_isalnum.c"
#include "test/ft_isascii.c"
#include "test/ft_isprint.c"
#include "test/ft_strlen.c"
#include "test/ft_memset.c"
#include "test/ft_bzero.c"
#include "test/ft_memcpy.c"
#include "test/ft_memmove.c"
#include "test/ft_strlcpy.c"
#include "test/ft_strlcat.c"
#include "test/ft_toupper.c"
#include "test/ft_tolower.c"
#include "test/ft_strchr.c"
#include "test/ft_strncmp.c"
#include "test/ft_memchr.c"
#include "test/ft_memcmp.c"
#include "test/ft_strnstr.c"
#include "test/ft_atoi.c"
#include "test/ft_calloc.c"
#include "test/ft_strdup.c"

// Part 2 - Additional functions
#include "test/ft_substr.c"
#include "test/ft_strjoin.c"
#include "test/ft_strtrim.c"
#include "test/ft_split.c"
#include "test/ft_itoa.c"
#include "test/ft_strmapi.c"
#include "test/ft_striteri.c"
#include "test/ft_putchar_fd.c"
#include "test/ft_putstr_fd.c"
#include "test/ft_putendl_fd.c"
#include "test/ft_putnbr_fd.c"

// Part 3 - Linked List
#include "test/ft_lstnew.c"
#include "test/ft_lstadd_front.c"
#include "test/ft_lstsize.c"
#include "test/ft_lstlast.c"
#include "test/ft_lstadd_back.c"
#include "test/ft_lstdelone.c"
#include "test/ft_lstclear.c"
#include "test/ft_lstiter.c"
#include "test/ft_lstmap.c"

#include "test/tester_test.c"
